<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<?php printf($this->translate('Hello again, %s.', __NAMESPACE__), $this->cmsUserDisplayName($this->user)); ?>
<br>
<br>
<?php

    $url = $this->url('cms-user/login', [], ['force_canonical' => true]);
    printf($this->translate('Your new password is: %s. Please, follow this link %s ' .
        'to log in with your new password.', __NAMESPACE__),
        $this->password,
        '<a href="' . $url . '">' . $url . '</a>');
