<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<?php printf($this->translate('Hello, %s.', __NAMESPACE__), $this->cmsUserDisplayName()); ?>
<br>
<br>
<?php

    $url = $this->url(
        null,
        ['action' => 'confirm-email', 'token' => $this->user->getRegistrationToken()],
        ['force_canonical' => true]
    );

    printf($this->translate('Please, follow this link %s to confirm your email.', __NAMESPACE__),
        '<a href="' . $url . '">' . $url . '</a>');
