<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<?php printf($this->translate('Hello, %s.', __NAMESPACE__), $this->cmsUserDisplayName($this->identity)); ?>
<br>
<br>
<?php

    $home = $this->url('home', [], ['force_canonical' => true]);
    $url  = $this->url(
        'cms-user/register/confirm',
        ['token' => $this->user->getRegistrationToken()],
        ['force_canonical' => true]
    );

    printf($this->translate('Welcome to %s. Please, follow this link %s ' .
        'to confirm your email and complete your registration.', __NAMESPACE__),
        '<a href="' . $home . '">' . $home . '</a>',
        '<a href="' . $url . '">' . $url . '</a>');
