<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<div class="alert alert-success">
<?php
    printf($this->translate('Confirmation successful! Your email address is %s.', __NAMESPACE__),
        '<strong>' . $this->identity->getEmail() . '</strong>');
?>
<?php if (!$this->cmsIdentity()): ?>
    <?php $url = $this->url('cms-user/login'); ?>
    <?php printf($this->translate('Please, follow this link %s to log into your account.', __NAMESPACE__),
        '<a href="' . $url . '">' . $url . '</a>'
     ); ?>
<?php endif; ?>
</div>
