<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/CmsUser for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
  <!-- <li>
    <a href="<?= $this->url('cms-user'); ?>">
      <?= $this->translate('User Home', __NAMESPACE__); ?>
    </a>
  </li> -->
  <li>
    <a href="<?= $this->url('cms-user/default', ['action' => 'edit-profile']); ?>">
      <?= $this->translate('Edit Profile', __NAMESPACE__); ?>
    </a>
  </li>
  <li>
    <a href="<?= $this->url('cms-user/default', ['action' => 'change-password']); ?>">
      <?= $this->translate('Change password', __NAMESPACE__); ?>
    </a>
  </li>
  <li>
    <a href="<?= $this->url('cms-user/default', ['action' => 'change-email']); ?>">
      <?= $this->translate('Change email', __NAMESPACE__); ?>
    </a>
  </li>
  <li>
    <a href="<?= $this->url('cms-user/default', ['action' => 'change-security-question']); ?>">
      <?= $this->translate('Change security question', __NAMESPACE__); ?>
    </a>
  </li>
