<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

echo $this->partial('cms-user/layout/nav-menu', array('navMenu' => $this->navMenu));

?>
<div class="jumbotron">
    <br />
    <h2><?php echo $this->errorMessage ?></h2>
    <br />
</div>
<?php echo $this->partial('error/index', ['display_exceptions' =>  $this->display_exceptions, 'exception' => $this->exception, 'message' => $this->exception->getMessage()]); ?>