<?php
/**
 * CoolMS2 User module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/coolms2 for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<div class="alert alert-warning">
<?php
    printf($this->translate('An email has been sent to %s. ' .
       'Please, check your inbox and confirm your request to change password!', __NAMESPACE__),
       '<strong>' . preg_replace_callback('/(.+?)(\@.+)/ui', function($matches) {
            return preg_replace('/[\w\d]/ui', '*', $matches[1]) . $matches[2];
        }, $this->identity->getEmail()) .'</strong>'
    );
?>
</div>
