<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

// Set translation and namespace options here
$this->formLabel()->setTranslatorTextDomain(__NAMESPACE__);
$this->legend()->setTranslatorTextDomain(__NAMESPACE__);
$this->formMessages()->setTranslatorTextDomain(__NAMESPACE__);
$this->formRow()->setTranslatorTextDomain(__NAMESPACE__);

// Set form fields classes and placeholders here
$form = $this->form;
$form->setAttributes([
        'class' => 'form-horizontal cms-form cmsuser-form cmsuser-form-reset-password',
        'role'  => 'form',
    ])->setLabelAttributes(['class' => 'panel-title']);

$form->get('identity')->setOption('twbs', [
    'icon' => [
        'content' => 'user',
        'placement' => 'prepend',
    ],
]);

$form->get('submit')->setValue('Reset Password')
    ->setOption('twbs', [
        'element' => ['class' => 'btn-block'],
        'col' => ['class' => 'col-xs-12 col-sm-8'],
        'reset' => [
            'type' => 'formGroupElement',
            'content' => 'reset',
            'order' => 9050,
            'placement' => 'append',
        ],
    ]);

if ($form->has('reset')) {
    $form->get('reset')->setOption('twbs', [
        'element' => ['class' => 'btn-block'],
        'col' => ['class' => 'col-xs-12 col-sm-4'],
    ]);
}

$form->prepare();

?>
<?= $this->form()->openTag($form); ?>
  <div class="panel panel-primary">
    <?php if($form->getLabel()): ?>
    <div class="panel-heading">
      <?= $this->icon('lock'); ?>&nbsp;&nbsp;<?= $this->formLabel($form); ?>
    </div>
    <?php endif; ?>
    <div class="panel-body">
      <?= $this->formMessages($form); ?>
      <?= $this->formRow($form->get('identity')); ?>
      <?= $this->formRow($form->get('birthdayVerify')); ?>
    </div>
    <div class="panel-footer clearfix">
      <?php if ($form->has('captcha')): ?>
        <?= $this->formRow($form->get('captcha')); ?>
      <?php endif; ?>
      <?php if ($form->has('csrf')): ?>
        <?= $this->formRow($form->get('csrf')); ?>
      <?php endif; ?>
      <?= $this->formRow($form->get('submit')); ?>
    </div>
  </div>
<?= $this->form()->closeTag();
