<?php
/**
 * CoolMS2 User Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/user for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<?= $this->render('layout/header'); ?>

<div class="container" id="content">
  <div class="row">
    <div class="col-sm-3 col-sm-push-9">
      <?= $this->render('layout/cmsuser-nav-menu'); ?>
    </div>
    <div class="col-sm-9 col-sm-pull-3">
      <?= $this->cmsMessages(null, ['class' => 'col-sm-12']); ?>
      <?= $this->content; ?>
    </div>
  </div>
</div> <!-- /container -->

<?= $this->render('layout/footer');