<?php
/**
 * CoolMS2 User module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/CmsUser for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

// use JQuery and Twitter Boostrap 3
$this->partial('twbs');
$this->partial('jquery');

?>
<?= $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle('CmsUser')->setSeparator(' | ')->setAutoEscape(false); ?>

    <!-- Meta -->
    <?= $this->headMeta(); ?>

    <!-- Styles -->
    <?= $this->headLink(); ?>

    <!-- Scripts -->
    <?= $this->headScript(); ?>
  </head>
  <body>
    <?= $this->partial('layout/cmsuser-header'); ?>

    <?= $this->partial('layout/cmsuser-region-leading'); ?>
    <?= $this->partial('layout/cmsuser-region-center'); ?>
    <?= $this->partial('layout/cmsuser-region-trailing'); ?>

    <?= $this->partial('layout/cmsuser-footer'); ?>
<?= $this->inlineScript(); ?>
  </body>
</html>
