<?php
/**
 * CoolMS2 User module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/CmsUser for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsUser;

?>
<?= $this->navigation('CmsUser\Navigation')->menu()->setUlClass($this->class ?: 'nav navbar-nav navbar-right')->setAddClassToListItem();
